version: '3.8'

services:
  youtube-extractor:
    build: .
    container_name: youtube-extractor-api
    ports:
      - "8000:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=False
      - USE_PROXIES=false
      - USE_BROWSER_COOKIES=false
      - MAX_REQUESTS_PER_MINUTE=30
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Redis para cache y rate limiting más avanzado
  redis:
    image: redis:7-alpine
    container_name: youtube-extractor-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: youtube-extractor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - youtube-extractor
    restart: unless-stopped

volumes:
  redis_data: